server:
  port: 8081
  servlet:
    context-path: /sell
spring:
  datasource:
    username: root
    password: a123
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/sell?characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
  jpa:
    show-sql: true
    properties:
      hibernate:
        enable_lazy_load_no_trans: true
  jackson:
    default-property-inclusion: non_null
  redis:
    host: localhost
    port: 6379
    password:
    database: 0
  freemarker:
   # request-context-attribute: req  #req访问request
    suffix: .ftl  #后缀名
    content-type: text/html
    enabled: true
    cache: false #缓存配置
    template-loader-path: classpath:/templates/ftl #模板加载路径 按需配置
    charset: UTF-8
    request-context-attribute: request
    expose-request-attributes: true
    expose-session-attributes: true
    expose-spring-macro-helpers: true
projecturl:
  sell: http://localhost:8081